name: Demo deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install packages
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: master
          folder: dist
          token: ${{ secrets.PAT }}
          repository-name: tsumo/tsumo.github.io
          target-folder: webgl-study
          commit-message: 'webgl-study (${{ github.event.head_commit.message }})'
